### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by steinhmor** [christiansicari/nextcloud-mail2deck#1]
When I try to run the main.py manualy to test it on my webserver I get the following error:

> python3 main.py 

>   File "main.py", line 24
>     if len(a := re.findall(regex, string)) > 0:
>                 ^
> SyntaxError: invalid syntax

(the ^ points on the : )

Is this a server-specific error or something else?
(sorry, I'm a absolute noob regarding python...)

**Comment by steinhmor** [comment]
it was a server-error

**Comment by christiansicari** [comment]
> it was a server-error

Not at all a server error. It is a new syntax coming with python 3.8 https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions
